version: "3.3"
 
networks:
  bbc-overlay:
    external:
      name: bbc-overlay
       
volumes:
  esdata:
 
services:
 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    networks:
      - bbc-overlay
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "network.host=0.0.0.0"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=true"
      - "xpack.watcher.enabled=false"
      - "xpack.ml.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
 
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    networks:
      - bbc-overlay
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"
